# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotaAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IotaBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IotaSeed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seed', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IotaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.TextField()),
                ('receiver_address', models.TextField()),
                ('bundle_hash', models.TextField()),
                ('value', models.BigIntegerField()),
                ('attachment_time', models.DateTimeField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('replay_count', models.BigIntegerField(default=0)),
                ('tail_transaction_hash', models.TextField(default='')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='iotaseed',
            unique_together=set([('user', 'seed')]),
        ),
        migrations.AddField(
            model_name='iotabalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iotaaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iotatransaction',
            unique_together=set([('bundle_hash', 'tail_transaction_hash')]),
        ),
        migrations.AlterUniqueTogether(
            name='iotaaddress',
            unique_together=set([('user', 'address')]),
        ),
    ]
