"""
Django settings for zendi project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'jk%)*05yip=9su+l=7mh6h_@-kyq9==bm6gfpw^#0%wyz!)@(q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nopassword',
    'django_extensions',
    'wallet'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zendi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zendi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTHENTICATION_BACKENDS = ('wallet.auth_backend.EmailBackend', 'django.contrib.auth.backends.ModelBackend')

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', './static_root/')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'wallet': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
            'propagate': False
        },
        'requests': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
            'propagate': False
        }
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
        'propagate': True
    }
}

# Nopassword settings
NOPASSWORD_LOGIN_CODE_TIMEOUT = 60 * 24 * 14  # in seconds

# User handling
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# SMTP credentials (local debug server)
EMAIL_HOST = 'localhost'
EMAIL_PORT = '1025'

# IOTA settings
# IOTA_NODE_URL = 'https://node.tangle.works:443/api/v1/commands'
# IOTA_NODE_URL = 'http://iota.bitfinex.com:80/api/v1/commands'
# IOTA_NODE_URL = 'http://wallets.iotamexico.com:80/api/v1/commands'
# IOTA_NODE_URL = 'http://service.iotasupport.com:14265/api/v1/commands'
# IOTA_NODE_URL = 'http://node01.iotatoken.nl:14265'
# IOTA_NODE_URL = 'http://node02.iotatoken.nl:14265'
# IOTA_NODE_URL = 'http://node03.iotatoken.nl:15265'
# IOTA_NODE_URL = 'http://node04.iotatoken.nl:14265'
# IOTA_NODE_URL = 'https://zendi.duckdns.org/iota_node/'
IOTA_NODE_URL = 'http://iota-node.duckdns.org:14265/api/v1/commands'
# IOTA_NODE_URL = 'https://nodes.iota.cafe:443'
IOTA_ROUTES = {
    'attachToTangle': 'http://iota-node.duckdns.org:14265/api/v1/commands',
    'broadcastTransactions': 'https://nodes.iota.cafe:443',
}
IOTA_SANDBOCK_AUTH_TOKEN = '03f7571a-bb6c-4a5d-86eb-0fd73f02da78'
IOTA_SANDBOX_URI = 'https://sandbox.iota.org/api/v1/'
IOTA_DEFAULT_DEPTH = 3
IOTA_REPLAY_INTERVAL = 60 * 30  # in seconds
IOTA_REPLAY_MAX_COUNT = 5  # max number of replays for a single transaction
