# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotaAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IotaSeed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seed', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userseed',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userseed',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSeed',
        ),
        migrations.AlterUniqueTogether(
            name='iotaseed',
            unique_together=set([('user', 'seed')]),
        ),
        migrations.AddField(
            model_name='iotaaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iotaaddress',
            unique_together=set([('user', 'address')]),
        ),
    ]
