# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotaAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('attached', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IotaExecutedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.TextField()),
                ('bundle_hash', models.TextField()),
                ('transaction_hash', models.TextField()),
                ('value', models.BigIntegerField()),
                ('execution_time', models.DateTimeField()),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='IotaSeed',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('seed', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userseed',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userseed',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSeed',
        ),
        migrations.AlterUniqueTogether(
            name='iotaseed',
            unique_together=set([('user', 'seed')]),
        ),
        migrations.AddField(
            model_name='iotaexecutedtransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iotaexecutedtransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iotaaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iotaaddress',
            unique_together=set([('user', 'address')]),
        ),
    ]
