# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20171015_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotaaddress',
            name='attached',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iotaseed',
            name='seed',
            field=models.BinaryField(unique=True),
        ),
    ]
