# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20171110_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotaaddress',
            name='attached',
        ),
    ]
