# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20171015_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotaseed',
            name='seed',
            field=models.TextField(unique=True),
        ),
    ]
