# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_iotabalance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IotaExecutedTransaction',
            new_name='IotaTransaction',
        ),
    ]
