# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_auto_20171015_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotaExecutedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_address', models.TextField()),
                ('bundle_hash', models.TextField()),
                ('transaction_hash', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('execution_time', models.DateTimeField()),
                ('message', models.TextField(default='')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
